name = "SpikeTriggered"
uuid = "3c99cc20-eaca-4e17-bd25-d7dac35e9bca"
authors = ["Yizhan Miao <yzmiao@pm.me>"]
version = "0.7.0"

[deps]
GSL = "92c85e6c-cbff-5e0c-80f7-495c94daaecd"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
