name = "SpikeTriggered"
uuid = "3c99cc20-eaca-4e17-bd25-d7dac35e9bca"
authors = ["Yizhan Miao <yzmiao@pm.me>"]
version = "0.1.4"

[deps]
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SDMS = "d0ac49df-e14a-4fbd-9c4a-cc834280f2a8"
